blueprint:
  name: "Raumlüftungsempfehlung (Feuchte + CO₂)"
  description: "Raumweise Lüftungsempfehlung basierend auf rel./abs. Luftfeuchtigkeit, optional CO₂, unter Berücksichtigung von Fensterstatus und Personenanwesenheit."
  domain: automation

  input:
    indoor_humidity:
      name: "Relative Luftfeuchtigkeit Innen (%)"
      selector:
        entity:
          domain: sensor
          device_class: humidity
    indoor_absolute:
      name: "Absolute Luftfeuchtigkeit Innen (g/m³)"
      selector:
        entity:
          domain: sensor
    outdoor_absolute:
      name: "Absolute Luftfeuchtigkeit Außen (g/m³)"
      selector:
        entity:
          domain: sensor
    window_sensors:
      name: "Fenstersensor(en) (optional)"
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class: window
          multiple: true
    presence_persons:
      name: "Personen zur Anwesenheit"
      default: []
      selector:
        entity:
          domain: person
          multiple: true
    co2_sensor:
      name: "Optionaler CO₂-Sensor"
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide
    threshold_relative:
      name: "Rel. LF-Schwelle (%)"
      default: 60
      selector:
        number:
          min: 40
          max: 80
          step: 1
    threshold_difference:
      name: "Absolute LF-Differenz Schwelle (g/m³)"
      default: 3
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
    co2_threshold:
      name: "CO₂-Schwelle (ppm)"
      default: 1200
      selector:
        number:
          min: 400
          max: 2000
          step: 50
    min_vent_duration:
      name: "Mindest-Lüftungsdauer (Minuten)"
      default: 10
      selector:
        number:
          min: 1
          max: 60
          step: 1
    repeat_interval:
      name: "Wiederholintervall (Minuten)"
      default: 30
      selector:
        number:
          min: 5
          max: 120
          step: 5
    time_start:
      name: "Start Zeitfenster"
      default: "06:00"
      selector:
        time:
    time_end:
      name: "End Zeitfenster"
      default: "22:00"
      selector:
        time:
        
mode: restart

variables:
  sensor_humidity: !input indoor_humidity
  sensor_absolute: !input indoor_absolute
  sensor_outdoor: !input outdoor_absolute
  sensor_windows: !input window_sensors
  sensor_persons: !input presence_persons
  sensor_co2: !input co2_sensor
  threshold_relative: !input threshold_relative
  threshold_difference: !input threshold_difference
  co2_threshold: !input co2_threshold
  min_vent_duration: !input min_vent_duration
  repeat_interval: !input repeat_interval
  time_start: !input time_start
  time_end: !input time_end
  
  rh_in: "{{ states(sensor_humidity) | float(0) }}"
  abs_in: "{{ states(sensor_absolute) | float(0) }}"
  abs_out: "{{ states(sensor_outdoor) | float(0) }}"
  diff: "{{ abs_in - abs_out }}"
  co2: >
    {% if sensor_co2 != '' %}
      {{ states(sensor_co2) | float(0) }}
    {% else %}
      0
    {% endif %}
  window_open: >
    {% if sensor_windows | length > 0 %}
      {{ expand(sensor_windows) | selectattr('state','eq','on') | list | count > 0 }}
    {% else %}
      false
    {% endif %}
  high_humidity: >
    {{ rh_in > threshold_relative and diff > threshold_difference }}
  bad_co2: >
    {% if sensor_co2 != '' %}
      {{ co2 > co2_threshold }}
    {% else %}
      false
    {% endif %}
  summer_block: >
    {{ abs_out > 14 and abs_out >= abs_in }}
  someone_home: >
    {% if sensor_persons | length > 0 %}
      {% set persons = expand(sensor_persons) %}
      {{ persons | selectattr('state','eq','home') | list | count > 0 }}
    {% else %}
      true
    {% endif %}
  within_time: >
    {% set now_time = now().time() %}
    {% set start = strptime(time_start, '%H:%M').time() %}
    {% set end = strptime(time_end, '%H:%M').time() %}
    {{ start <= now_time <= end }}
  should_vent: >
    {{ within_time and someone_home and not summer_block and (high_humidity or bad_co2) and not window_open }}
  should_close: >
    {{ window_open and (diff < 1 or rh_in < 55 or abs_in < abs_out) }}
  warn_window_open_absent: >
    {{ not someone_home and window_open and (sensor_windows | length > 0) }}

trigger:
  - platform: state
    entity_id: !input indoor_humidity
  - platform: state
    entity_id: !input indoor_absolute
  - platform: state
    entity_id: !input outdoor_absolute
  - platform: state
    entity_id: !input window_sensors
  - platform: state
    entity_id: !input presence_persons
  - platform: state
    entity_id: !input co2_sensor

action:
  - choose:
      - conditions: "{{ should_vent }}"
        sequence:
          - action: notify.mobile_app_iphone_von_chris
            data:
              message: >
                Lüften empfohlen! Innen: {{ rh_in | round(1) }} % rF, Differenz: {{ diff | round(1) }} g/m³{% if sensor_co2 != '' %}, CO₂: {{ co2 | round(0) }} ppm{% endif %}
              title: "Lüften"
          - delay:
              minutes: "{{ repeat_interval }}"
      - conditions: "{{ should_close }}"
        sequence:
          - delay:
              minutes: "{{ min_vent_duration }}"
          - action: notify.mobile_app_iphone_von_chris
            data:
              message: >
                Fenster schließen empfohlen! Innen: {{ rh_in | round(1) }} % rF, Differenz: {{ diff | round(1) }} g/m³
              title: "Fenster schließen"
      - conditions: "{{ warn_window_open_absent }}"
        sequence:
          - action: notify.mobile_app_iphone_von_chris
            data:
              message: "Achtung: Fenster noch offen, während niemand zuhause ist!"
              title: "Fenster offen"
