blueprint:
  name: "Raumlüftungsempfehlung Komplett (Feuchte + CO₂ + Anwesenheit über Personen, optional Fenster)"
  description: "Raumweise Lüftungsempfehlung und Fenster-Schließen-Empfehlung basierend auf relativer und absoluter Luftfeuchtigkeit, optional CO₂, Fensterstatus, Personenanwesenheit, Sommer-/Winterlogik und Smart Reset."
  domain: automation

  input:
    indoor_humidity:
      name: "Relative Luftfeuchtigkeit Innen"
      selector:
        entity:
          domain: sensor
    indoor_absolute:
      name: "Absolute Luftfeuchtigkeit Innen (g/m³)"
      selector:
        entity:
          domain: sensor
    outdoor_absolute:
      name: "Absolute Luftfeuchtigkeit Außen (g/m³)"
      selector:
        entity:
          domain: sensor
    window_sensors:
      name: "Fenstersensor(en) (optional)"
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class: window
          multiple: true
    notify_device:
      name: "Benachrichtigungsgerät"
      selector:
        device:
          integration: mobile_app
    presence_persons:
      name: "Personen zur Anwesenheit"
      default: []
      selector:
        entity:
          domain: person
          multiple: true
    threshold_relative:
      name: "Rel. LF-Schwelle (%)"
      default: 60
      selector:
        number:
          min: 40
          max: 80
          step: 1
    threshold_difference:
      name: "Absolute LF-Differenz Schwelle (g/m³)"
      default: 3
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
    co2_sensor:
      name: "Optionaler CO₂-Sensor"
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide
          multiple: false
    co2_threshold:
      name: "CO₂-Schwelle (ppm)"
      default: 1200
      selector:
        number:
          min: 400
          max: 2000
          step: 50
    min_vent_duration:
      name: "Mindest-Lüftungsdauer (Minuten)"
      default: 10
      selector:
        number:
          min: 1
          max: 60
          step: 1
    repeat_interval:
      name: "Wiederholintervall (Minuten)"
      default: 30
      selector:
        number:
          min: 5
          max: 120
          step: 5
    critical_push:
      name: "Kritische Push-Nachricht aktivieren?"
      default: false
      selector:
        boolean:
    create_status_entity:
      name: "Status-Entity erstellen?"
      default: false
      selector:
        boolean:
    time_start:
      name: "Start Zeitfenster"
      default: "06:00"
      selector:
        time:
    time_end:
      name: "End Zeitfenster"
      default: "22:00"
      selector:
        time:

mode: restart

variables:
  sensor_humidity: !input indoor_humidity
  sensor_absolute: !input indoor_absolute
  sensor_outdoor: !input outdoor_absolute
  sensor_windows: !input window_sensors
  sensor_notify: !input notify_device
  sensor_persons: !input presence_persons
  sensor_co2: !input co2_sensor
  threshold_relative: !input threshold_relative
  threshold_difference: !input threshold_difference
  co2_threshold: !input co2_threshold
  min_vent_duration: !input min_vent_duration
  repeat_interval: !input repeat_interval
  critical_push: !input critical_push

trigger:
  - platform: state
    entity_id: "{{ sensor_humidity }}"
  - platform: state
    entity_id: "{{ sensor_absolute }}"
  - platform: state
    entity_id: "{{ sensor_outdoor }}"
  - platform: state
    entity_id: "{{ sensor_windows }}"
  - platform: state
    entity_id: "{{ sensor_co2 }}"
  - platform: state
    entity_id: "{{ sensor_persons }}"

variables:
  rh_in: "{{ states(sensor_humidity) | float(0) }}"
  abs_in: "{{ states(sensor_absolute) | float(0) }}"
  abs_out: "{{ states(sensor_outdoor) | float(0) }}"
  diff: "{{ abs_in - abs_out }}"
  co2: >
    {% if sensor_co2 != '' %}
      {{ states(sensor_co2) | float(0) }}
    {% else %}
      0
    {% endif %}
  window_open: >
    {% if sensor_windows | length > 0 %}
      {{ expand(sensor_windows) | selectattr('state','eq','on') | list | count > 0 }}
    {% else %}
      false
    {% endif %}
  high_humidity: >
    {{ rh_in > threshold_relative | float and diff > threshold_difference | float }}
  bad_co2: >
    {% if sensor_co2 != '' %}
      {{ co2 > co2_threshold | float }}
    {% else %}
      false
    {% endif %}
  summer_block: >
    {{ abs_out > 14 and abs_out >= abs_in }}
  someone_home: >
    {% if sensor_persons | length > 0 %}
      {% set persons = expand(sensor_persons) %}
      {{ persons | selectattr('state','eq','home') | list | count > 0 }}
    {% else %}
      true
    {% endif %}
  within_time: >
    {% set now_time = now().strftime('%H:%M') %}
    {{ now_time >= !input('time_start') and now_time <= !input('time_end') }}
  should_vent: >
    {{ within_time and someone_home and not summer_block and (high_humidity or bad_co2) and not window_open }}
  should_close: >
    {{ window_open and (diff < 1 or rh_in < 55 or abs_in > abs_out) }}
  warn_window_open_absent: >
    {{ not someone_home and window_open and (sensor_windows | length > 0) }}

action:
  - choose:
      - conditions: "{{ should_vent }}"
        sequence:
          - device_id: "{{ sensor_notify }}"
            domain: mobile_app
            type: notify
            data:
              message: >
                "Lüften empfohlen! Innen: {{ rh_in | round(1) }} % rF, Differenz: {{ diff | round(1) }} g/m³, CO₂: {% if sensor_co2 != '' %}{{ co2 | round(0) }} ppm{% else %}nicht gemessen{% endif %}"
              title: "{% if not critical_push %}Lüften{% else %}Lüften (kritisch){% endif %}"
          - delay:
              minutes: "{{ repeat_interval }}"
      - conditions: "{{ should_close }}"
        sequence:
          - delay:
              minutes: "{{ min_vent_duration }}"
          - device_id: "{{ sensor_notify }}"
            domain: mobile_app
            type: notify
            data:
              message: >
                "Fenster schließen empfohlen! Innen: {{ rh_in | round(1) }} % rF, Differenz: {{ diff | round(1) }} g/m³"
              title: "{% if not critical_push %}Fenster schließen{% else %}Fenster schließen (kritisch){% endif %}"
      - conditions: "{{ warn_window_open_absent }}"
        sequence:
          - device_id: "{{ sensor_notify }}"
            domain: mobile_app
            type: notify
            data:
              message: "Achtung: Fenster noch offen, während niemand zuhause ist!"
              title: "{% if not critical_push %}Fenster offen{% else %}Fenster offen (kritisch){% endif %}"
  - choose:
      - conditions: "{{ !input('create_status_entity') }}"
        sequence: []
      - conditions: "{{ not !input('create_status_entity') }}"
        sequence:
          - service: input_text.set_value
            data:
              entity_id: input_text.lueftung_status
              value: >
                {% if should_vent %}Lüften empfohlen{% elif should_close %}Schließen empfohlen{% elif warn_window_open_absent %}Fenster offen{% else %}Keine Aktion{% endif %}
